<?php
//	USE THIS FOR DATABASE ACCES 
/*	
$cn=mysql_connect("localhost","root","") or die (mysql_error());
mysql_select_db("test");
$strstring="select * from product where name like '".$_POST['q']."%' order by name limit 0,10";
$rs=mysql_query($strstring,$cn) or die(mysql_error().">>>".$strstring);
$result = array();
while ($row=mysql_fetch_array($rs))	{
	array_push($result, array("id"=>$row['id'],"value" => $row['name']));
};
echo json_encode($result);
*/
// USE THIS FOR ARRAY ACCESS
$result = array();
array_push($result, array("id"=>"001","value" => "afghanistan"));
array_push($result, array("id"=>"002","value" => "albania"));
array_push($result, array("id"=>"003","value" => "algeria"));
array_push($result, array("id"=>"004","value" => "andorra"));
array_push($result, array("id"=>"005","value" => "angola"));
array_push($result, array("id"=>"006","value" => "antigua and barbuda"));
array_push($result, array("id"=>"007","value" => "argentina"));
array_push($result, array("id"=>"008","value" => "armenia"));
array_push($result, array("id"=>"009","value" => "australia"));
array_push($result, array("id"=>"010","value" => "austria"));
array_push($result, array("id"=>"011","value" => "azerbaijan"));
array_push($result, array("id"=>"012","value" => "bahamas"));
array_push($result, array("id"=>"013","value" => "bahrain"));
array_push($result, array("id"=>"014","value" => "bangladesh"));
array_push($result, array("id"=>"015","value" => "barbados"));
array_push($result, array("id"=>"016","value" => "belarus"));
array_push($result, array("id"=>"017","value" => "belgium"));
array_push($result, array("id"=>"018","value" => "belize"));
array_push($result, array("id"=>"019","value" => "benin"));
array_push($result, array("id"=>"020","value" => "bhutan"));
array_push($result, array("id"=>"021","value" => "bolivia"));
array_push($result, array("id"=>"022","value" => "bosnia and herzegovina"));
array_push($result, array("id"=>"023","value" => "botswana"));
array_push($result, array("id"=>"024","value" => "brazil"));
array_push($result, array("id"=>"025","value" => "brunei"));
array_push($result, array("id"=>"026","value" => "bulgaria"));
array_push($result, array("id"=>"027","value" => "burkina faso"));
array_push($result, array("id"=>"028","value" => "burundi"));
array_push($result, array("id"=>"029","value" => "cambodia"));
array_push($result, array("id"=>"030","value" => "cameroon"));
array_push($result, array("id"=>"031","value" => "canada"));
array_push($result, array("id"=>"032","value" => "cape verde"));
array_push($result, array("id"=>"033","value" => "central african republic"));
array_push($result, array("id"=>"034","value" => "chad"));
array_push($result, array("id"=>"035","value" => "chile"));
array_push($result, array("id"=>"036","value" => "china"));
array_push($result, array("id"=>"037","value" => "colombi"));
array_push($result, array("id"=>"038","value" => "comoros"));
array_push($result, array("id"=>"039","value" => "congo (brazzaville)"));
array_push($result, array("id"=>"040","value" => "congo"));
array_push($result, array("id"=>"041","value" => "costa rica"));
array_push($result, array("id"=>"042","value" => "cote d'ivoire"));
array_push($result, array("id"=>"043","value" => "croatia"));
array_push($result, array("id"=>"044","value" => "cuba"));
array_push($result, array("id"=>"045","value" => "cyprus"));
array_push($result, array("id"=>"046","value" => "czech republic"));
array_push($result, array("id"=>"047","value" => "denmark"));
array_push($result, array("id"=>"048","value" => "djibouti"));
array_push($result, array("id"=>"049","value" => "dominica"));
array_push($result, array("id"=>"050","value" => "dominican republic"));
array_push($result, array("id"=>"051","value" => "east timor (timor timur)"));
array_push($result, array("id"=>"052","value" => "ecuador"));
array_push($result, array("id"=>"053","value" => "egypt"));
array_push($result, array("id"=>"054","value" => "el salvador"));
array_push($result, array("id"=>"055","value" => "equatorial guinea"));
array_push($result, array("id"=>"056","value" => "eritrea"));
array_push($result, array("id"=>"057","value" => "estonia"));
array_push($result, array("id"=>"058","value" => "ethiopia"));
array_push($result, array("id"=>"059","value" => "fiji"));
array_push($result, array("id"=>"060","value" => "finland"));
array_push($result, array("id"=>"061","value" => "france"));
array_push($result, array("id"=>"062","value" => "gabon"));
array_push($result, array("id"=>"063","value" => "gambia, the"));
array_push($result, array("id"=>"064","value" => "georgia"));
array_push($result, array("id"=>"065","value" => "germany"));
array_push($result, array("id"=>"066","value" => "ghana"));
array_push($result, array("id"=>"067","value" => "greece"));
array_push($result, array("id"=>"068","value" => "grenada"));
array_push($result, array("id"=>"069","value" => "guatemala"));
array_push($result, array("id"=>"070","value" => "guinea"));
array_push($result, array("id"=>"071","value" => "guinea-bissau"));
array_push($result, array("id"=>"072","value" => "guyana"));
array_push($result, array("id"=>"073","value" => "haiti"));
array_push($result, array("id"=>"074","value" => "honduras"));
array_push($result, array("id"=>"075","value" => "hungary"));
array_push($result, array("id"=>"076","value" => "iceland"));
array_push($result, array("id"=>"077","value" => "india"));
array_push($result, array("id"=>"078","value" => "indonesia"));
array_push($result, array("id"=>"079","value" => "iran"));
array_push($result, array("id"=>"080","value" => "iraq"));
array_push($result, array("id"=>"081","value" => "ireland"));
array_push($result, array("id"=>"082","value" => "israel"));
array_push($result, array("id"=>"083","value" => "italy"));
array_push($result, array("id"=>"084","value" => "jamaica"));
array_push($result, array("id"=>"085","value" => "japan"));
array_push($result, array("id"=>"086","value" => "jordan"));
array_push($result, array("id"=>"087","value" => "kazakhstan"));
array_push($result, array("id"=>"088","value" => "kenya"));
array_push($result, array("id"=>"089","value" => "kiribati"));
array_push($result, array("id"=>"090","value" => "korea, north"));
array_push($result, array("id"=>"091","value" => "korea, south"));
array_push($result, array("id"=>"092","value" => "kuwait"));
array_push($result, array("id"=>"093","value" => "kyrgyzstan"));
array_push($result, array("id"=>"094","value" => "laos"));
array_push($result, array("id"=>"095","value" => "latvia"));
array_push($result, array("id"=>"096","value" => "lebanon"));
array_push($result, array("id"=>"097","value" => "lesotho"));
array_push($result, array("id"=>"098","value" => "liberia"));
array_push($result, array("id"=>"099","value" => "libya"));
array_push($result, array("id"=>"100","value" => "liechtenstein"));
array_push($result, array("id"=>"101","value" => "lithuania"));
array_push($result, array("id"=>"102","value" => "luxembourg"));
array_push($result, array("id"=>"103","value" => "macedonia"));
array_push($result, array("id"=>"104","value" => "madagascar"));
array_push($result, array("id"=>"105","value" => "malawi"));
array_push($result, array("id"=>"106","value" => "malaysia"));
array_push($result, array("id"=>"107","value" => "maldives"));
array_push($result, array("id"=>"108","value" => "mali"));
array_push($result, array("id"=>"109","value" => "malta"));
array_push($result, array("id"=>"110","value" => "marshall islands"));
array_push($result, array("id"=>"111","value" => "mauritania"));
array_push($result, array("id"=>"112","value" => "mauritius"));
array_push($result, array("id"=>"113","value" => "mexico"));
array_push($result, array("id"=>"114","value" => "micronesia"));
array_push($result, array("id"=>"115","value" => "moldova"));
array_push($result, array("id"=>"116","value" => "monaco"));
array_push($result, array("id"=>"117","value" => "mongolia"));
array_push($result, array("id"=>"118","value" => "morocco"));
array_push($result, array("id"=>"119","value" => "mozambique"));
array_push($result, array("id"=>"120","value" => "myanmar"));
array_push($result, array("id"=>"121","value" => "namibia"));
array_push($result, array("id"=>"122","value" => "nauru"));
array_push($result, array("id"=>"123","value" => "nepal"));
array_push($result, array("id"=>"124","value" => "netherlands"));
array_push($result, array("id"=>"125","value" => "new zealand"));
array_push($result, array("id"=>"126","value" => "nicaragua"));
array_push($result, array("id"=>"127","value" => "niger"));
array_push($result, array("id"=>"128","value" => "nigeria"));
array_push($result, array("id"=>"129","value" => "norway"));
array_push($result, array("id"=>"130","value" => "oman"));
array_push($result, array("id"=>"131","value" => "pakistan"));
array_push($result, array("id"=>"132","value" => "palau"));
array_push($result, array("id"=>"133","value" => "panama"));
array_push($result, array("id"=>"134","value" => "papua new guinea"));
array_push($result, array("id"=>"135","value" => "paraguay"));
array_push($result, array("id"=>"136","value" => "peru"));
array_push($result, array("id"=>"137","value" => "philippines"));
array_push($result, array("id"=>"138","value" => "poland"));
array_push($result, array("id"=>"139","value" => "portugal"));
array_push($result, array("id"=>"140","value" => "qatar"));
array_push($result, array("id"=>"141","value" => "romania"));
array_push($result, array("id"=>"142","value" => "russia"));
array_push($result, array("id"=>"143","value" => "rwanda"));
array_push($result, array("id"=>"144","value" => "saint kitts and nevis"));
array_push($result, array("id"=>"145","value" => "saint lucia"));
array_push($result, array("id"=>"146","value" => "saint vincent"));
array_push($result, array("id"=>"147","value" => "samoa"));
array_push($result, array("id"=>"148","value" => "san marino"));
array_push($result, array("id"=>"149","value" => "sao tome and principe"));
array_push($result, array("id"=>"150","value" => "saudi arabia"));
array_push($result, array("id"=>"151","value" => "senegal"));
array_push($result, array("id"=>"152","value" => "serbia and montenegro"));
array_push($result, array("id"=>"153","value" => "seychelles"));
array_push($result, array("id"=>"154","value" => "sierra leone"));
array_push($result, array("id"=>"155","value" => "singapore"));
array_push($result, array("id"=>"156","value" => "slovakia"));
array_push($result, array("id"=>"157","value" => "slovenia"));
array_push($result, array("id"=>"158","value" => "solomon islands"));
array_push($result, array("id"=>"159","value" => "somalia"));
array_push($result, array("id"=>"160","value" => "south africa"));
array_push($result, array("id"=>"161","value" => "spain"));
array_push($result, array("id"=>"162","value" => "sri lanka"));
array_push($result, array("id"=>"163","value" => "sudan"));
array_push($result, array("id"=>"164","value" => "suriname"));
array_push($result, array("id"=>"165","value" => "swaziland"));
array_push($result, array("id"=>"166","value" => "sweden"));
array_push($result, array("id"=>"167","value" => "switzerland"));
array_push($result, array("id"=>"168","value" => "syria"));
array_push($result, array("id"=>"169","value" => "taiwan"));
array_push($result, array("id"=>"170","value" => "tajikistan"));
array_push($result, array("id"=>"171","value" => "tanzania"));
array_push($result, array("id"=>"172","value" => "thailand"));
array_push($result, array("id"=>"173","value" => "togo"));
array_push($result, array("id"=>"174","value" => "tonga"));
array_push($result, array("id"=>"175","value" => "trinidad and tobago"));
array_push($result, array("id"=>"176","value" => "tunisia"));
array_push($result, array("id"=>"177","value" => "turkey"));
array_push($result, array("id"=>"178","value" => "turkmenistan"));
array_push($result, array("id"=>"179","value" => "tuvalu"));
array_push($result, array("id"=>"180","value" => "uganda"));
array_push($result, array("id"=>"181","value" => "ukraine"));
array_push($result, array("id"=>"182","value" => "united arab emirates"));
array_push($result, array("id"=>"183","value" => "united kingdom"));
array_push($result, array("id"=>"184","value" => "united states"));
array_push($result, array("id"=>"185","value" => "uruguay"));
array_push($result, array("id"=>"186","value" => "uzbekistan"));
array_push($result, array("id"=>"187","value" => "vanuatu"));
array_push($result, array("id"=>"188","value" => "vatican city"));
array_push($result, array("id"=>"199","value" => "venezuela"));
array_push($result, array("id"=>"190","value" => "vietnam"));
array_push($result, array("id"=>"191","value" => "yemen"));
array_push($result, array("id"=>"192","value" => "zambia"));
array_push($result, array("id"=>"193","value" => "zimbabwe"));
echo json_encode($result);
?>
